plugins {
    id 'java-library'
    id 'maven-publish'
}

apply from: "$rootDir/buildSource.gradle"

def apiMavenRepoDir = (findProperty("stemcraftApiRepoDir")
    ?: System.getenv("MAVEN_REPO_DIR")
    ?: "/repos/maven/maven-public").toString()

repositories {
    mavenCentral()
    maven { url = uri("https://repo.papermc.io/repository/maven-public/") }
    maven { url = uri("https://repo.opencollab.dev/main/") }
    maven { url = uri("https://maven.enginehub.org/repo/") }
}

dependencies {
    //noinspection VulnerableLibrariesLocal
    compileOnly("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")

    // WorldEdit
    compileOnly("com.sk89q.worldedit:worldedit-bukkit:7.3.17")

    // GeyserMC API
    compileOnly('org.geysermc.geyser:api:2.9.0-SNAPSHOT')

    // LuckPerms
    compileOnly 'net.luckperms:api:5.4'

    // Lombok
    compileOnly "org.projectlombok:lombok:1.18.32"
    annotationProcessor "org.projectlombok:lombok:1.18.32"

    // Jackson for JSON handling
    compileOnly("com.fasterxml.jackson.core:jackson-databind:2.19.4")
    implementation("com.fasterxml.jackson.core:jackson-core:2.19.4")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.19.4")
}
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
            artifactId = "stemcraft-api"
            version = project.version.toString()
        }
    }
    repositories {
        maven { url = uri(new File(apiMavenRepoDir)) }
    }
}

tasks.named("jar", Jar) {
    archiveBaseName.set("STEMCraft-API")

    archiveVersion.set("${project.version}${getArchiveBuildMetadata()}")
}
